# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QNarcis
                                 A QGIS plugin
 Narcis GIS assistant
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-21
        copyright            : (C) 2023 by Acme inc.
        email                : acme@acme.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QNarcis class from file QNarcis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .q_narcis import QNarcis
    return QNarcis(iface)
